package com.jzyuchen.ssm.dao;

import com.jzyuchen.ssm.model.WeixinConfiguration;
import com.jzyuchen.ssm.model.WeixinConfigurationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface WeixinConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_wx_config
     *
     * @mbggenerated
     */
    @Delete({
        "delete from org_wx_config",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_wx_config
     *
     * @mbggenerated
     */
    @Insert({
        "insert into org_wx_config (id, orgid, ",
        "appid, appsecret, ",
        "verify_url, creatime, ",
        "updatetime, status)",
        "values (#{id,jdbcType=INTEGER}, #{orgid,jdbcType=INTEGER}, ",
        "#{appid,jdbcType=VARCHAR}, #{appsecret,jdbcType=VARCHAR}, ",
        "#{verifyUrl,jdbcType=VARCHAR}, #{creatime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP}, #{status,jdbcType=BIT})"
    })
    int insert(WeixinConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_wx_config
     *
     * @mbggenerated
     */
    int insertSelective(WeixinConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_wx_config
     *
     * @mbggenerated
     */
    List<WeixinConfiguration> selectByExample(WeixinConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_wx_config
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, orgid, appid, appsecret, verify_url, creatime, updatetime, status",
        "from org_wx_config",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WeixinConfiguration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_wx_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_wx_config
     *
     * @mbggenerated
     */
    @Update({
        "update org_wx_config",
        "set orgid = #{orgid,jdbcType=INTEGER},",
          "appid = #{appid,jdbcType=VARCHAR},",
          "appsecret = #{appsecret,jdbcType=VARCHAR},",
          "verify_url = #{verifyUrl,jdbcType=VARCHAR},",
          "creatime = #{creatime,jdbcType=TIMESTAMP},",
          "updatetime = #{updatetime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WeixinConfiguration record);
}