package com.jzyuchen.ssm.dao;

import com.jzyuchen.ssm.model.WeixinAccessToken;
import com.jzyuchen.ssm.model.WeixinAccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface WeixinAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_access_token
     *
     * @mbggenerated
     */
    @Delete({
        "delete from weixin_access_token",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_access_token
     *
     * @mbggenerated
     */
    @Insert({
        "insert into weixin_access_token (id, app_id, ",
        "access_token, expires_in, ",
        "created_at, updated_at)",
        "values (#{id,jdbcType=INTEGER}, #{appId,jdbcType=VARCHAR}, ",
        "#{accessToken,jdbcType=VARCHAR}, #{expiresIn,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(WeixinAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_access_token
     *
     * @mbggenerated
     */
    int insertSelective(WeixinAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_access_token
     *
     * @mbggenerated
     */
    List<WeixinAccessToken> selectByExample(WeixinAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_access_token
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, app_id, access_token, expires_in, created_at, updated_at",
        "from weixin_access_token",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WeixinAccessToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_access_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_access_token
     *
     * @mbggenerated
     */
    @Update({
        "update weixin_access_token",
        "set app_id = #{appId,jdbcType=VARCHAR},",
          "access_token = #{accessToken,jdbcType=VARCHAR},",
          "expires_in = #{expiresIn,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WeixinAccessToken record);
}