package com.jzyuchen.ssm.model;

import java.util.Date;

public class WeixinAccessToken extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_access_token.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_access_token.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_access_token.access_token
     *
     * @mbggenerated
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_access_token.expires_in
     *
     * @mbggenerated
     */
    private Integer expiresIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_access_token.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_access_token.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_access_token
     *
     * @mbggenerated
     */
    public WeixinAccessToken(Integer id, String appId, String accessToken, Integer expiresIn) {
        this.id = id;
        this.appId = appId;
        this.accessToken = accessToken;
        this.expiresIn = expiresIn;
        this.createdAt = new Date();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_access_token
     *
     * @mbggenerated
     */
    public WeixinAccessToken() {
        super();
        this.createdAt = new Date();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_access_token.id
     *
     * @return the value of weixin_access_token.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_access_token.id
     *
     * @param id the value for weixin_access_token.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_access_token.app_id
     *
     * @return the value of weixin_access_token.app_id
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_access_token.app_id
     *
     * @param appId the value for weixin_access_token.app_id
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_access_token.access_token
     *
     * @return the value of weixin_access_token.access_token
     * @mbggenerated
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_access_token.access_token
     *
     * @param accessToken the value for weixin_access_token.access_token
     * @mbggenerated
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_access_token.expires_in
     *
     * @return the value of weixin_access_token.expires_in
     * @mbggenerated
     */
    public Integer getExpiresIn() {
        return expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_access_token.expires_in
     *
     * @param expiresIn the value for weixin_access_token.expires_in
     * @mbggenerated
     */
    public void setExpiresIn(Integer expiresIn) {
        this.expiresIn = expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_access_token.created_at
     *
     * @return the value of weixin_access_token.created_at
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_access_token.created_at
     *
     * @param createdAt the value for weixin_access_token.created_at
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_access_token.updated_at
     *
     * @return the value of weixin_access_token.updated_at
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_access_token.updated_at
     *
     * @param updatedAt the value for weixin_access_token.updated_at
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public boolean isExpired() {
        Date now = new Date();
        return now.getTime() > (this.createdAt.getTime() + this.expiresIn * 1000);
    }
}