package com.jzyuchen.ssm.model;

import java.util.Date;

public class WeixinConfiguration extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_wx_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_wx_config.orgid
     *
     * @mbggenerated
     */
    private Integer orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_wx_config.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_wx_config.appsecret
     *
     * @mbggenerated
     */
    private String appsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_wx_config.verify_url
     *
     * @mbggenerated
     */
    private String verifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_wx_config.creatime
     *
     * @mbggenerated
     */
    private Date creatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_wx_config.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_wx_config.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_wx_config
     *
     * @mbggenerated
     */
    public WeixinConfiguration(Integer id, Integer orgid, String appid, String appsecret, String verifyUrl, Date creatime, Date updatetime, Boolean status) {
        this.id = id;
        this.orgid = orgid;
        this.appid = appid;
        this.appsecret = appsecret;
        this.verifyUrl = verifyUrl;
        this.creatime = creatime;
        this.updatetime = updatetime;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_wx_config
     *
     * @mbggenerated
     */
    public WeixinConfiguration() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_wx_config.id
     *
     * @return the value of org_wx_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_wx_config.id
     *
     * @param id the value for org_wx_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_wx_config.orgid
     *
     * @return the value of org_wx_config.orgid
     *
     * @mbggenerated
     */
    public Integer getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_wx_config.orgid
     *
     * @param orgid the value for org_wx_config.orgid
     *
     * @mbggenerated
     */
    public void setOrgid(Integer orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_wx_config.appid
     *
     * @return the value of org_wx_config.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_wx_config.appid
     *
     * @param appid the value for org_wx_config.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_wx_config.appsecret
     *
     * @return the value of org_wx_config.appsecret
     *
     * @mbggenerated
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_wx_config.appsecret
     *
     * @param appsecret the value for org_wx_config.appsecret
     *
     * @mbggenerated
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_wx_config.verify_url
     *
     * @return the value of org_wx_config.verify_url
     *
     * @mbggenerated
     */
    public String getVerifyUrl() {
        return verifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_wx_config.verify_url
     *
     * @param verifyUrl the value for org_wx_config.verify_url
     *
     * @mbggenerated
     */
    public void setVerifyUrl(String verifyUrl) {
        this.verifyUrl = verifyUrl == null ? null : verifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_wx_config.creatime
     *
     * @return the value of org_wx_config.creatime
     *
     * @mbggenerated
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_wx_config.creatime
     *
     * @param creatime the value for org_wx_config.creatime
     *
     * @mbggenerated
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_wx_config.updatetime
     *
     * @return the value of org_wx_config.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_wx_config.updatetime
     *
     * @param updatetime the value for org_wx_config.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_wx_config.status
     *
     * @return the value of org_wx_config.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_wx_config.status
     *
     * @param status the value for org_wx_config.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}